//! IPC message types for WinTermDriver.
//!
//! All messages follow the envelope format from §13.5:
//! ```json
//! { "id": "uuid-string", "type": "message-type-name", "payload": { ... } }
//! ```
//!
//! Each payload struct implements [`MessagePayload`] which provides the wire
//! type name. The [`Envelope`] type handles serialization to/from the envelope
//! format.

use serde::{Deserialize, Serialize};
use serde_json::Value;

// ---------------------------------------------------------------------------
// Envelope
// ---------------------------------------------------------------------------

/// Wire envelope: `{ "id": "...", "type": "...", "payload": { ... } }`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Envelope {
    /// Correlation/tracking UUID generated by the sender.
    pub id: String,
    /// Message type discriminator.
    #[serde(rename = "type")]
    pub msg_type: String,
    /// Type-specific payload.
    #[serde(default = "default_payload")]
    pub payload: Value,
}

fn default_payload() -> Value {
    Value::Object(serde_json::Map::new())
}

impl Envelope {
    /// Create an envelope from a typed payload.
    pub fn new<P: MessagePayload>(id: impl Into<String>, payload: &P) -> Self {
        Self {
            id: id.into(),
            msg_type: P::TYPE_NAME.to_owned(),
            payload: serde_json::to_value(payload).expect("payload serialization is infallible"),
        }
    }

    /// Extract the payload into a concrete type.
    pub fn extract_payload<P: MessagePayload>(&self) -> Result<P, serde_json::Error> {
        serde_json::from_value(self.payload.clone())
    }
}

// ---------------------------------------------------------------------------
// MessagePayload trait
// ---------------------------------------------------------------------------

/// Trait implemented by every IPC payload type, providing the wire type name.
pub trait MessagePayload: Serialize + for<'de> Deserialize<'de> {
    /// The string that appears in the `"type"` field of the envelope.
    const TYPE_NAME: &'static str;
}

/// Look up the type name → payload deserializer for any known message type.
/// Returns the deserialized payload as a [`TypedMessage`].
pub fn parse_envelope(envelope: &Envelope) -> Result<TypedMessage, ParseError> {
    macro_rules! dispatch {
        ($($variant:ident => $ty:ty),+ $(,)?) => {
            match envelope.msg_type.as_str() {
                $( <$ty>::TYPE_NAME => {
                    let p: $ty = serde_json::from_value(envelope.payload.clone())
                        .map_err(ParseError::InvalidPayload)?;
                    Ok(TypedMessage::$variant(p))
                } )+
                other => Err(ParseError::UnknownType(other.to_owned())),
            }
        };
    }

    dispatch! {
        // Client → Host
        Handshake           => Handshake,
        OpenWorkspace       => OpenWorkspace,
        AttachWorkspace     => AttachWorkspace,
        CloseWorkspace      => CloseWorkspace,
        RecreateWorkspace   => RecreateWorkspace,
        SaveWorkspace       => SaveWorkspace,
        ListWorkspaces      => ListWorkspaces,
        ListInstances       => ListInstances,
        ListPanes           => ListPanes,
        ListSessions        => ListSessions,
        Send                => Send,
        Prompt              => Prompt,
        Keys                => Keys,
        Mouse               => Mouse,
        PaneInput           => PaneInput,
        Capture             => Capture,
        Scrollback          => Scrollback,
        Follow              => Follow,
        CancelFollow        => CancelFollow,
        Inspect             => Inspect,
        Notify              => Notify,
        ClearAttention      => ClearAttention,
        SetPaneStatus       => SetPaneStatus,
        ConfigurePane       => ConfigurePane,
        InvokeAction        => InvokeAction,
        SessionInput        => SessionInput,
        PaneResize          => PaneResize,
        FocusPane           => FocusPane,
        RenamePane          => RenamePane,
        // Host → Client
        HandshakeAck        => HandshakeAck,
        OkResponse          => OkResponse,
        ErrorResponse       => ErrorResponse,
        OpenWorkspaceResult => OpenWorkspaceResult,
        AttachWorkspaceResult   => AttachWorkspaceResult,
        RecreateWorkspaceResult => RecreateWorkspaceResult,
        ListWorkspacesResult    => ListWorkspacesResult,
        ListInstancesResult     => ListInstancesResult,
        ListPanesResult     => ListPanesResult,
        ListSessionsResult  => ListSessionsResult,
        CaptureResult       => CaptureResult,
        ScrollbackResult    => ScrollbackResult,
        InspectResult       => InspectResult,
        AttentionChanged    => AttentionChanged,
        InvokeActionResult  => InvokeActionResult,
        FollowData          => FollowData,
        FollowEnd           => FollowEnd,
        SessionOutput       => SessionOutput,
        SessionStateChanged => SessionStateChanged,
        TitleChanged        => TitleChanged,
        ProgressChanged     => ProgressChanged,
        LayoutChanged       => LayoutChanged,
        WorkspaceStateChanged => WorkspaceStateChanged,
    }
}

/// Error returned by [`parse_envelope`].
#[derive(Debug, thiserror::Error)]
pub enum ParseError {
    #[error("unknown message type: {0}")]
    UnknownType(String),
    #[error("invalid payload: {0}")]
    InvalidPayload(serde_json::Error),
}

/// Fully typed message, produced by [`parse_envelope`].
#[derive(Debug, Clone, PartialEq)]
pub enum TypedMessage {
    // Client → Host
    Handshake(Handshake),
    OpenWorkspace(OpenWorkspace),
    AttachWorkspace(AttachWorkspace),
    CloseWorkspace(CloseWorkspace),
    RecreateWorkspace(RecreateWorkspace),
    SaveWorkspace(SaveWorkspace),
    ListWorkspaces(ListWorkspaces),
    ListInstances(ListInstances),
    ListPanes(ListPanes),
    ListSessions(ListSessions),
    Send(Send),
    Prompt(Prompt),
    Keys(Keys),
    Mouse(Mouse),
    PaneInput(PaneInput),
    Capture(Capture),
    Scrollback(Scrollback),
    Follow(Follow),
    CancelFollow(CancelFollow),
    Inspect(Inspect),
    Notify(Notify),
    ClearAttention(ClearAttention),
    SetPaneStatus(SetPaneStatus),
    ConfigurePane(ConfigurePane),
    InvokeAction(InvokeAction),
    SessionInput(SessionInput),
    PaneResize(PaneResize),
    FocusPane(FocusPane),
    RenamePane(RenamePane),
    // Host → Client
    HandshakeAck(HandshakeAck),
    OkResponse(OkResponse),
    ErrorResponse(ErrorResponse),
    OpenWorkspaceResult(OpenWorkspaceResult),
    AttachWorkspaceResult(AttachWorkspaceResult),
    RecreateWorkspaceResult(RecreateWorkspaceResult),
    ListWorkspacesResult(ListWorkspacesResult),
    ListInstancesResult(ListInstancesResult),
    ListPanesResult(ListPanesResult),
    ListSessionsResult(ListSessionsResult),
    CaptureResult(CaptureResult),
    ScrollbackResult(ScrollbackResult),
    InspectResult(InspectResult),
    AttentionChanged(AttentionChanged),
    InvokeActionResult(InvokeActionResult),
    FollowData(FollowData),
    FollowEnd(FollowEnd),
    SessionOutput(SessionOutput),
    SessionStateChanged(SessionStateChanged),
    TitleChanged(TitleChanged),
    ProgressChanged(ProgressChanged),
    LayoutChanged(LayoutChanged),
    WorkspaceStateChanged(WorkspaceStateChanged),
}

// ---------------------------------------------------------------------------
// Macro to reduce boilerplate for payload impls
// ---------------------------------------------------------------------------

macro_rules! impl_payload {
    ($ty:ty, $name:expr) => {
        impl MessagePayload for $ty {
            const TYPE_NAME: &'static str = $name;
        }
    };
}

// ===================================================================
// Client → Host payload types
// ===================================================================

/// §13.6 — Initial handshake sent by client on connection.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Handshake {
    /// `"ui"` or `"cli"`.
    pub client_type: ClientType,
    pub client_version: String,
    pub protocol_version: u32,
}
impl_payload!(Handshake, "Handshake");

/// Client type in the handshake.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ClientType {
    Ui,
    Cli,
}

/// §13.14 — Open (or reuse) a workspace instance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenWorkspace {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    #[serde(default)]
    pub recreate: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
}
impl_payload!(OpenWorkspace, "OpenWorkspace");

/// §13.11 — Attach UI to a running workspace instance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AttachWorkspace {
    pub workspace: String,
}
impl_payload!(AttachWorkspace, "AttachWorkspace");

/// §13.14 — Close a workspace instance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CloseWorkspace {
    pub workspace: String,
    #[serde(default)]
    pub kill: bool,
}
impl_payload!(CloseWorkspace, "CloseWorkspace");

/// §13.14 — Recreate a workspace instance from its definition.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecreateWorkspace {
    pub workspace: String,
}
impl_payload!(RecreateWorkspace, "RecreateWorkspace");

/// §13.14 — Save workspace state to a file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveWorkspace {
    pub workspace: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
}
impl_payload!(SaveWorkspace, "SaveWorkspace");

/// §13.14 — List known workspace definitions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListWorkspaces {}
impl_payload!(ListWorkspaces, "ListWorkspaces");

/// §13.14 — List running workspace instances.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListInstances {}
impl_payload!(ListInstances, "ListInstances");

/// §13.14 — List panes in a workspace.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListPanes {
    pub workspace: String,
}
impl_payload!(ListPanes, "ListPanes");

/// §13.14 — List sessions in a workspace.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListSessions {
    pub workspace: String,
}
impl_payload!(ListSessions, "ListSessions");

/// §13.14 — Send text to a target pane's session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Send {
    pub target: String,
    pub text: String,
    #[serde(default = "default_true")]
    pub newline: bool,
}
impl_payload!(Send, "Send");

fn default_true() -> bool {
    true
}

/// §13.14 — Send a pane-configured prompt to a target session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Prompt {
    pub target: String,
    pub text: String,
}
impl_payload!(Prompt, "Prompt");

/// §13.14 — Send key sequences to a target pane's session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Keys {
    pub target: String,
    pub keys: Vec<String>,
}
impl_payload!(Keys, "Keys");

/// Button identifier for semantic mouse injection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MouseButton {
    Left,
    Middle,
    Right,
    None,
}

/// Mouse event kind for semantic mouse injection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MouseKind {
    Press,
    Release,
    Click,
    Move,
    WheelUp,
    WheelDown,
}

fn default_repeat() -> u16 {
    1
}

/// §13.14 — Inject semantic mouse input into a target pane's session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Mouse {
    pub target: String,
    pub kind: MouseKind,
    /// 0-based cell column.
    pub col: u16,
    /// 0-based cell row.
    pub row: u16,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub button: Option<MouseButton>,
    #[serde(default)]
    pub shift: bool,
    #[serde(default)]
    pub alt: bool,
    #[serde(default)]
    pub ctrl: bool,
    #[serde(default = "default_repeat")]
    pub repeat: u16,
    #[serde(default)]
    pub force: bool,
}
impl_payload!(Mouse, "Mouse");

/// §13.14 — Send raw bytes to a target pane's session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaneInput {
    pub target: String,
    /// Base64-encoded input bytes.
    pub data: String,
}
impl_payload!(PaneInput, "PaneInput");

/// §13.14 — Capture screen content from a target pane.
///
/// Precedence for what to return:
/// 1. Anchor found (`after`/`after_regex`) → from match line to end
/// 2. Anchor not found → fall back to `lines`/`all`/visible
/// 3. `lines` → last N lines (scrollback + visible, from bottom)
/// 4. `all` → entire buffer (all scrollback + visible)
/// 5. Nothing → visible screen only
///
/// `max_lines` always caps the output (trims oldest first).
/// `count` suppresses text and returns metadata only.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Capture {
    /// Required: target pane path.
    pub target: String,
    /// Return a replayable VT snapshot of the current visible screen state.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vt: Option<bool>,
    /// Return last N lines (scrollback + visible, counted from bottom).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lines: Option<u32>,
    /// Return entire buffer (all scrollback + visible).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub all: Option<bool>,
    /// Exact substring anchor — search newest-first in scrollback, capture from match line to end.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    /// Regex anchor — same search behavior as `after`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after_regex: Option<String>,
    /// Cap total lines returned (trims oldest if exceeded).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_lines: Option<u32>,
    /// Return metadata only (line count, anchor status), no text.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<bool>,
}
impl_payload!(Capture, "Capture");

/// §13.14 — Retrieve scrollback from a target pane.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Scrollback {
    pub target: String,
    pub tail: u32,
}
impl_payload!(Scrollback, "Scrollback");

/// §13.10 — Subscribe to streaming output from a target pane.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Follow {
    pub target: String,
    #[serde(default)]
    pub raw: bool,
}
impl_payload!(Follow, "Follow");

/// §13.10 — Cancel an active follow subscription.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CancelFollow {
    /// The `id` of the original Follow request to cancel.
    pub id: String,
}
impl_payload!(CancelFollow, "CancelFollow");

/// §13.14 — Inspect a target pane/session for full metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Inspect {
    pub target: String,
}
impl_payload!(Inspect, "Inspect");

/// Structured attention state for panes and workspaces.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AttentionState {
    Active,
    NeedsAttention,
    Done,
    Error,
}

impl Default for AttentionState {
    fn default() -> Self {
        Self::Active
    }
}

/// §13.14 — Publish an attention notification for a target pane.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Notify {
    pub target: String,
    pub state: AttentionState,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}
impl_payload!(Notify, "Notify");

/// §13.14 — Clear a target pane's attention state back to active.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClearAttention {
    pub target: String,
}
impl_payload!(ClearAttention, "ClearAttention");

/// §13.14 — Publish structured pane metadata/status for a hosted agent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetPaneStatus {
    pub target: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress: Option<ProgressInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub queue_pending: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}
impl_payload!(SetPaneStatus, "SetPaneStatus");

/// §13.14 — Update pane-local metadata such as prompt driver settings.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfigurePane {
    pub target: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub driver_profile: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub submit_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub soft_break_key: Option<String>,
    #[serde(default)]
    pub clear_soft_break: bool,
    #[serde(default)]
    pub clear_driver: bool,
}
impl_payload!(ConfigurePane, "ConfigurePane");

/// §13.12 — Invoke an action (from keybinding, chord, or command palette).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InvokeAction {
    pub action: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_pane_id: Option<String>,
    #[serde(default)]
    pub args: Value,
}
impl_payload!(InvokeAction, "InvokeAction");

/// §13.12 — Forward raw keyboard input bytes to a session (fire-and-forget).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionInput {
    pub workspace: String,
    pub session_id: String,
    /// Base64-encoded input bytes.
    pub data: String,
}
impl_payload!(SessionInput, "SessionInput");

/// §13.12 — Resize a pane.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaneResize {
    pub pane_id: String,
    pub cols: u16,
    pub rows: u16,
}
impl_payload!(PaneResize, "PaneResize");

/// §13.14 — Set focus to a pane.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FocusPane {
    pub pane_id: String,
}
impl_payload!(FocusPane, "FocusPane");

/// §13.14 — Rename a pane.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RenamePane {
    pub pane_id: String,
    pub new_name: String,
}
impl_payload!(RenamePane, "RenamePane");

// ===================================================================
// Host → Client payload types
// ===================================================================

/// §13.6 — Handshake acknowledgment from host.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HandshakeAck {
    pub host_version: String,
    pub protocol_version: u32,
    pub access_policy: AccessPolicy,
}
impl_payload!(HandshakeAck, "HandshakeAck");

/// Local access policy enforced by the host for this connection.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AccessPolicy {
    pub transport: AccessTransport,
    pub scope: AccessScope,
    pub identity: AccessIdentity,
    pub remote_access: bool,
}

impl Default for AccessPolicy {
    fn default() -> Self {
        Self::same_user_local()
    }
}

impl AccessPolicy {
    pub fn same_user_local() -> Self {
        Self {
            transport: AccessTransport::WindowsNamedPipe,
            scope: AccessScope::SameUserLocal,
            identity: AccessIdentity::CurrentUserSid,
            remote_access: false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AccessTransport {
    WindowsNamedPipe,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AccessScope {
    SameUserLocal,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AccessIdentity {
    CurrentUserSid,
}

/// Generic success response.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OkResponse {}
impl_payload!(OkResponse, "Ok");

/// §13.8 — Error response with structured error code.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorResponse {
    pub code: ErrorCode,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub candidates: Option<Vec<String>>,
}
impl_payload!(ErrorResponse, "Error");

/// §13.8 — Defined error codes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "target-not-found")]
    TargetNotFound,
    #[serde(rename = "target-ambiguous")]
    TargetAmbiguous,
    #[serde(rename = "workspace-not-found")]
    WorkspaceNotFound,
    #[serde(rename = "workspace-already-exists")]
    WorkspaceAlreadyExists,
    #[serde(rename = "invalid-action")]
    InvalidAction,
    #[serde(rename = "invalid-argument")]
    InvalidArgument,
    #[serde(rename = "session-failed")]
    SessionFailed,
    #[serde(rename = "definition-error")]
    DefinitionError,
    #[serde(rename = "protocol-error")]
    ProtocolError,
    #[serde(rename = "internal-error")]
    InternalError,
}

/// §13.14 — Result of opening a workspace.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenWorkspaceResult {
    pub instance_id: String,
    /// Snapshot of the workspace instance state.
    #[serde(default)]
    pub state: Value,
}
impl_payload!(OpenWorkspaceResult, "OpenWorkspaceResult");

/// §13.11 — Full workspace state returned on UI attach.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AttachWorkspaceResult {
    /// Snapshot of the workspace instance state (windows, tabs, panes, sessions).
    #[serde(default)]
    pub state: Value,
}
impl_payload!(AttachWorkspaceResult, "AttachWorkspaceResult");

/// §13.14 — Result of recreating a workspace.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecreateWorkspaceResult {
    pub instance_id: String,
    #[serde(default)]
    pub state: Value,
}
impl_payload!(RecreateWorkspaceResult, "RecreateWorkspaceResult");

/// §13.14 — List of workspace definitions with their sources.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListWorkspacesResult {
    pub workspaces: Vec<WorkspaceInfo>,
}
impl_payload!(ListWorkspacesResult, "ListWorkspacesResult");

/// Summary info for a workspace definition.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceInfo {
    pub name: String,
    pub source: String,
}

/// §13.14 — List of running workspace instances.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListInstancesResult {
    pub instances: Vec<InstanceInfo>,
}
impl_payload!(ListInstancesResult, "ListInstancesResult");

/// Summary info for a running workspace instance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InstanceInfo {
    pub name: String,
    pub instance_id: String,
}

/// §13.7/§13.14 — List of panes with metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListPanesResult {
    pub panes: Vec<PaneInfo>,
}
impl_payload!(ListPanesResult, "ListPanesResult");

/// Summary info for a pane.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaneInfo {
    pub name: String,
    pub tab: String,
    pub session_state: String,
    #[serde(default)]
    pub attention: AttentionState,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attention_message: Option<String>,
}

/// §13.14 — List of sessions with metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListSessionsResult {
    pub sessions: Vec<SessionInfo>,
}
impl_payload!(ListSessionsResult, "ListSessionsResult");

/// Summary info for a session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionInfo {
    pub session_id: String,
    pub pane: String,
    pub state: String,
}

/// §13.14 — Result of a Capture request.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct CaptureResult {
    /// Captured text (empty when `count` mode was requested).
    pub text: String,
    /// Number of lines in `text` (or would-be count when `count` mode).
    #[serde(default)]
    pub lines: u32,
    /// Total lines available in the buffer (scrollback + visible).
    #[serde(default)]
    pub total_lines: u32,
    /// Whether the anchor was found (only set when `after`/`after_regex` was requested).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub anchor_found: Option<bool>,
    /// Absolute line index where the capture started (0 = oldest scrollback).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<u32>,
    /// Visible terminal width in cells.
    #[serde(default)]
    pub cols: u16,
    /// Visible terminal height in cells.
    #[serde(default)]
    pub rows: u16,
    /// Whether the active visible buffer is the alternate screen.
    #[serde(default)]
    pub on_alternate: bool,
    /// Current session title from OSC 0/2.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Current session/tab progress from OSC 9;4.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress: Option<ProgressInfo>,
    /// Current mouse tracking mode.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mouse_mode: Option<String>,
    /// Whether SGR mouse mode (1006) is active.
    #[serde(default)]
    pub sgr_mouse: bool,
    /// Whether bracketed paste mode (2004) is active.
    #[serde(default)]
    pub bracketed_paste: bool,
    /// Cursor row within the visible screen (0-based).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor_row: Option<u16>,
    /// Cursor column within the visible screen (0-based).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor_col: Option<u16>,
    /// Whether the cursor is visible.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor_visible: Option<bool>,
    /// Current cursor shape.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor_shape: Option<String>,
}
impl_payload!(CaptureResult, "CaptureResult");

/// §13.14 — Scrollback lines.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScrollbackResult {
    pub lines: Vec<String>,
}
impl_payload!(ScrollbackResult, "ScrollbackResult");

/// §13.14 — Full metadata for a pane/session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InspectResult {
    /// Full metadata — exact structure depends on the target.
    #[serde(flatten)]
    pub data: Value,
}
impl_payload!(InspectResult, "InspectResult");

/// §13.13 — Pane or workspace attention changed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AttentionChanged {
    pub workspace: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pane_id: Option<String>,
    pub state: AttentionState,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}
impl_payload!(AttentionChanged, "AttentionChanged");

/// Result of invoking an action (§18.1–18.3).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InvokeActionResult {
    /// Outcome kind: `"ok"`, `"pane-created"`, or `"pane-closed"`.
    pub result: String,
    /// New or closed pane ID (present for pane-created and pane-closed).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pane_id: Option<String>,
}
impl_payload!(InvokeActionResult, "InvokeActionResult");

/// §13.10 — Streaming output chunk (text or raw).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FollowData {
    /// Decoded text (when raw=false) or base64-encoded bytes (when raw=true).
    pub text: String,
}
impl_payload!(FollowData, "FollowData");

/// §13.10 — Follow stream terminated.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FollowEnd {
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}
impl_payload!(FollowEnd, "FollowEnd");

/// §13.9 — Raw VT output pushed to UI clients (base64-encoded).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionOutput {
    pub workspace: String,
    pub session_id: String,
    /// Base64-encoded VT bytes.
    pub data: String,
}
impl_payload!(SessionOutput, "SessionOutput");

/// §13.13 — Session state transition notification.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionStateChanged {
    pub workspace: String,
    pub session_id: String,
    pub new_state: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}
impl_payload!(SessionStateChanged, "SessionStateChanged");

/// §13.13 — Session title changed (from VT escape sequence).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TitleChanged {
    pub workspace: String,
    pub session_id: String,
    pub title: String,
}
impl_payload!(TitleChanged, "TitleChanged");

/// WT-style progress state for a terminal tab/session (OSC 9;4).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProgressState {
    Normal,
    Error,
    Indeterminate,
    Warning,
}

/// Terminal progress indicator payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProgressInfo {
    pub state: ProgressState,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<u8>,
}

/// §13.13 — Session progress changed (from OSC 9;4).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProgressChanged {
    pub workspace: String,
    pub session_id: String,
    pub progress: Option<ProgressInfo>,
}
impl_payload!(ProgressChanged, "ProgressChanged");

/// §13.13 — Tab layout tree changed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LayoutChanged {
    pub workspace: String,
    pub window: String,
    pub tab: String,
    /// Full PaneRuntimeNode tree for the tab.
    pub layout: Value,
}
impl_payload!(LayoutChanged, "LayoutChanged");

/// §13.14 — Workspace instance state transition.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceStateChanged {
    pub workspace: String,
    pub new_state: String,
}
impl_payload!(WorkspaceStateChanged, "WorkspaceStateChanged");

/// Named pipe path prefix for the current user (§13.1).
///
/// The full path is `\\.\pipe\wtd-{user-SID}`. The SID segment is filled in
/// at runtime by the host process.
pub fn pipe_name_prefix() -> &'static str {
    r"\\.\pipe\wtd-"
}
